# Configure a small IX peering network
---
- hosts: rservers
  gather_facts: false
  roles:
    - role: bird_bgp
      tags: [ rservers ]

- hosts: routers
  gather_facts: false
  roles:
    - role: eos_system
      tags: [ routers, system ] 
    - role: eos_interfaces
      tags: [ routers, interfaces ] 
    - role: eos_bgp_ixp
      tags: [ routers, bgp ]

- hosts: ixp
  gather_facts: false
  roles:
    - role: eos_system
      tags: [ ixp, system ]

- hosts: isp
  gather_facts: false
  roles:
    - role: eos_static
      tags: [ isp, static ]