# Configure a 2 tier clos
---
- hosts: eos
  gather_facts: false

  roles:
    - role: eos_system
      tags: [ routers, system ]
    - role: eos_interfaces
      tags: [ routers, interfaces ]
    - role: eos_bgp_underlay
      tags: [ routers, underlay ]
    - role: eos_bgp_overlay
      tags: [ routers, overlay ]

- hosts: hosts
  gather_facts: false
  roles:
    - role: eos_system
      tags: [ hosts, system ]

# Uniquely pass vars to each host in the playbook instead of using host_vars as
# different playbook setups will use different IPs, VLANs etc for the same host
- hosts: ceos-host1
  gather_facts: false
  roles:
    - role: eos_host
      tags: hosts
  vars:
    vrfs:
      - name: "TENANT-A-100"
        ip: "192.168.100.12/24"
        id: 100
      - name: "TENANT-A-101"
        ip: "192.168.101.12/24"
        id: 101
    interfaces:
      Ethernet1: "ceos-leaf1:eth5"
      Ethernet2: "ceos-leaf2:eth5"


  