# Configure a 2 tier clos
---
- hosts: eos
  gather_facts: false

  roles:
   - eos_system
   - eos_interfaces
   - eos_bgp_underlay
   - eos_bgp_overlay

- hosts: hosts
  gather_facts: false

  # We put host variables in the playbook itself as
  # we will use host roles in other playbooks/labs
  # that will have different setups
  vars:
    ceos-host1:
      vrfs:
        - name: "TENANT-A-100"
          ip: "192.168.100.12/24"
          id: 100
        - name: "TENANT-A-101"
          ip: "192.168.101.12/24"
          id: 101
          routing: true
      interfaces:
        Ethernet1: "ceos-leaf1:eth5"
        Ethernet2: "ceos-leaf2:eth5"

  roles:
   - eos_host
  