# Configure a small IX peering network
---
- hosts: rservers
  gather_facts: false
  roles:
    - role: bird_bgp
      tags: [ rservers ]

- hosts: routers
  gather_facts: false
  roles:
    - role: eos_device
      tags: [ routers ] 

- hosts: switches
  gather_facts: false
  roles:
    - role: eos_device
      tags: [ switches ]