# Configure a small IX peering network
---
- hosts: rservers
  gather_facts: false
  roles:
    - role: bird_bgp
      tags: [ rservers ]

- hosts: peers
  gather_facts: false
  roles:
    - role: eos_system
      tags: [ peers, system ] 
    - role: eos_interfaces
      tags: [ peers, interfaces ] 
    - role: eos_bgp_ixp
      tags: [ peers, bgp ]

- hosts: ixp
  gather_facts: false
  roles:
    - role: eos_system
      tags: [ ixp, system ]
#    - role: eos_interfaces
#      tags: [ ixp, interfaces ] 