---
- hosts: eos
  gather_facts: false

  tasks:
  - name: Verify you can connect to your device(s) and get output
    eos_command:
      commands:
        - show hostname
        - show ip interface management 0  
    register: version_details

  - name: Display result
    debug:
      var: version_details.stdout_lines