# Create the /etc/bird/bird.conf file relevant to the lab deployment
# and then run bird
---

- name: Create bird.conf
  ansible.builtin.copy:
    src: "../templates/bird.conf.j2"
    dest: /etc/bird/bird.conf
    owner: bird
    group: bird
    mode: u=rw,g=r,o=r
  become: yes

- name: Stop BIRD
  ansible.builtin.command: service bird stop
  become: yes

- name: Run BIRD
  ansible.builtin.command: /usr/sbin/bird -u bird -g bird -c /etc/bird/bird.conf 
  become: yes