# Unnumbered BGP routing
---
- name: Enable IPv4+6 routing
  eos_config:
    lines:
      - "ip routing"
      - "ip routing ipv6 interface"
      - "ipv6 unicast-routing"

- name: Configure BGP 
  arista.eos.eos_bgp_global:
    config:
      as_number: "{{ bgp['local_as'] }}"
      log_neighbor_changes: True
      router_id: "{{ router_id }}"
      neighbor:
        - neighbor_address: {{ bgp['peer_group'] }}
          peer_group: {{ bgp['peer_group'] }}
          send_community:
            - set: true
          allowas_in:
            - count: 1
  when: 
    - bgp is defined

- name: Configure Address Families
  arista.eos.eos_bgp_address_family:
    config:
      as_number: "{{ bgp['local_as']}}"
      address_family:
        - afi: "ipv4"
          network: 
            - address: "{{ router_id }}/32" # TBD: Convert to direct reference to loopback0 address
          neighbor:
            - peer: "{{ bgp['peer_group'] }}"
              activate: True
              # next_hop_address_family: "ipv6" # ipv6 originate doesn't seem to be supported
  when: 
    - bgp.peer_group is defined

# Doesn't look like interface based neighbors are supuported in eos_bgp module yet so need to use eos_config
# https://docs.ansible.com/ansible/latest/collections/arista/eos/eos_bgp_global_module.html
- name: Configure BGP Unnumbered neighbors
  eos_config:
    lines:
      - "neighbor interface {{item.if}} peer-group {{item.peer_group}} remote-as {{item.remote_as}}"
    parents:
      - "router bgp {{bgp['local_as']}}"
  when: 
    - bgp.neighbors is defined
  loop: "{{ bgp.neighbors.unnumbered }}"

# Can't get ipv6 originate working in eos_bgp_address_family either
- name: Configure ipv6 originate
  eos_config:
    lines:
      - "neighbor {{ bgp['peer_group'] }} next-hop address-family ipv6 originate"
    parents:
      - "router bgp {{bgp['local_as']}} address-family ipv4"