---
- name: Device configuration to be applied
  ansible.builtin.debug:
    msg: "{{ lookup('template', '../templates/conf_eos_device.j2') }}"

- name: Apply device configuration
  arista.eos.eos_config:
    src: "../templates/conf_eos_device.j2"
    timeout: 60