{
 "title": "Arista Telemetry",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "eos diagram",
   "type": "canvas",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (interface_name) (rate(gnmic_eos_interface_stats_out_octets{source=\"eos1\"}[$__rate_interval]) + rate(gnmic_eos_interface_stats_in_octets{source=\"eos1\"}[$__rate_interval]))",
     "legendFormat": "eos1/{{interface_name}}-total"
    },
    {
     "expr": "rate(gnmic_eos_interface_stats_out_octets{source=\"eos2\"}[$__rate_interval]) + rate(gnmic_eos_interface_stats_in_octets{source=\"eos2\"}[$__rate_interval])",
     "legendFormat": "{{source}}/{{interface_name}}-total"
    }
   ]
  },
  {
   "title": "Interface traffic stats (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(gnmic_eos_interface_stats_in_octets[$__rate_interval])",
     "legendFormat": "{{source}}/{{interface_name}} - in bytes"
    },
    {
     "expr": "rate(gnmic_eos_interface_stats_out_octets[$__rate_interval])",
     "legendFormat": "{{source}}/{{interface_name}} - out bytes"
    }
   ]
  },
  {
   "title": "Number of received BGP routes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_eos_bgp_neighbors_installed{afi_safi_afi_safi_name=\"IPV4_UNICAST\"}",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "gnmic_eos_cpu_avg{job=\"gnmic\"}",
     "legendFormat": "{{source}}/{{component_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gnmic_eos_mem_utilized{component_name=\"Chassis\"}",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}