---
- name: J2 Config to be applied
  vars:
    output: "{{ lookup('template', '../templates/eos_interfaces.conf.j2') }}"
  tasks:
    - name: Print J2
      debug:
        msg: "{{ output }}"

- name: Apply Interface configuration via J2
  arista.eos.eos_config:
    src: "../templates/eos_interfaces.conf.j2"