---
# Anycast Server configuration

bgp:
  type: "anycast_server"
  router_id: "10.0.0.121"
  local_as: 65201
  sessions:
    - name: "CEOS-LEAF1"
      remote_as: 65101
      neighbors:
        - ip: "10.0.0.111"
          ipv6: "2001:2:b1::1"
          desc: "To CEOS-LEAF1"