---
# Specific Device configuration
#
# Interfaces, IPs, Routing, etc.
system:
  type: "router"
  
# Interfaces (Management already done by Containerlab)
interfaces:
  - if: "Loopback0"
    desc: "Underlay Loopback"
    ipv4: "10.0.0.101/32"
    ipv6: "2001:2:a1::1/128"
  - if: "Ethernet1"
    desc: "ceos-spine1:Ethernet1 --> ceos-leaf1:Ethernet1"
    ipv6: "LLA"
  - if: "Ethernet2"
    desc: "ceos-spine1:Ethernet2 --> ceos-leaf2:Ethernet1"
    ipv6: "LLA"
  - if: "Ethernet3"
    desc: "ceos-spine1:Ethernet3 --> ceos-leaf3:Ethernet1"
    ipv6: "LLA"
  - if: "Ethernet4"
    desc: "ceos-spine1:Ethernet4 --> ceos-leaf4:Ethernet1"
    ipv6: "LLA"
  - if: "Ethernet5"
    desc: "ceos-spine1:Ethernet5 --> ceos-bdr1:Ethernet1"
    ipv4: "10.255.0.2/31"
    ipv6: "LLA"

# Routing
static:
  ipv4:
    - prefix: "172.16.1.0/24"
      dest: "Null0"
  ipv6:
    - prefix: "2002::/48"
      dest: "Null0"

bgp:
  router_id: 10.0.0.101
  local_as: 65000
  type: [ "external", "spine" ]
  underlay_name: "PG_UNDERLAY"    
  sessions:
    - name: "BDR"
      local_as: 100
      remote_as: 300
      neighbors:
        - ip: "10.255.0.3"
          pg: "BDR-IPV4"
          desc: "To ceos-bdr1 - v4"
        - ip: "2002::10:255:0:3"
          pg: "BDR-IPV6"
          desc: "To ceos-bdr1 - v6"
      prefixes_v4_out:
        - prefix: "172.16.1.0/24"
          action: "permit"
      prefixes_v6_out:
        - prefix: "2002::/48"
          action: "permit"
      routemaps_v4_in:
        - action: "permit"
          pfl: "PL-ANY-INBOUND"
        - action: "deny"
      routemaps_v4_out:
        - action: "permit"
          pfl: "PL-BDR-OUTBOUND"
        - action: "deny"
      routemaps_v6_in:
        - action: "permit"
          pfl: "PL-ANY-INBOUND-V6"
        - action: "deny"
      routemaps_v6_out:
        - action: "permit"
          pfl: "PL-BDR-OUTBOUND-V6"
        - action: "deny"

        

