---
# Route Server configuration

router_id: 192.168.0.252
as_number: 64500
peers:
  - name: "CEOS-PEER1"
    desc: "To ceos-peer1"
    ip: "192.168.0.11"
    as_number: 64501
  - name: "CEOS-PEER2"
    desc: "To ceos-peer2"
    ip: "192.168.0.12"
    as_number: 64502
  - name: "CEOS-PEER3"
    desc: "To ceos-peer3"
    ip: "192.168.0.13"
    as_number: 64503