---
# Specific Device configuration
#
# Interfaces, IPs, Routing, etc.

# Interfaces (Management already done by Containerlab)
interfaces:
  - if: "Loopback0"
    desc: "Loopback"
    enabled: true
    ipv4: "10.255.4.1/32"
    ipv6: "2001:db8:c4::1/128"
    ospf:
      area: "0.0.0.0"
      passive: true
    ospfv3:
      area: "0.0.0.0"
      passive: true
  - if: "Ethernet1"
    desc: "ceos-r4:Ethernet1 --> ceos-r3:Ethernet1"
    enabled: true
    routed: true
    ipv4: "10.101.255.9/31"
    ipv6: "2001:db8:c3c4::c4c3/64"
    ospf:
      area: "0.0.0.0"
    ospfv3:
      area: "0.0.0.0"
  - if: "Ethernet2"
    desc: "ceos-r4:Ethernet2 --> ceos-r2:Ethernet2"
    enabled: true
    routed: true
    ipv4: "10.101.255.7/31"
    ipv6: "2001:db8:c2c4::c4c2/64"
    ospf:
      area: "0.0.0.0"
    ospfv3:
      area: "0.0.0.0"

# Routing
router_id: 10.255.4.1
