---
# Specific Device configuration
#
# Interfaces, IPs, Routing, etc.

# Interfaces (Management already done by Containerlab)
interfaces:
  - if: "Loopback0"
    desc: "Loopback"
    enabled: true
    ipv4: "10.0.0.11/32"
    ipv6: "2001:db8:b1::1/128"
  - if: "Ethernet1"
    desc: "ceos-spine1:Ethernet1 --> ceos-leaf1:Ethernet1"
    enabled: true
    routed: true
    v6: true
  - if: "Ethernet2"
    desc: "ceos-spine1:Ethernet2 --> ceos-leaf2:Ethernet1"
    enabled: true
    routed: true
    v6: true

# Routing
router_id: 10.0.0.11
bgp:
  local_as: 65000
  peer_group: "LEAF"
  neighbors:
    unnumbered:
      - if: "Et1"
        peer_group: "LEAF"
        remote_as: 65101
      - if: "Et2"
        peer_group: "LEAF"
        remote_as: 65102
        

