---
# Specific Device configuration
#
# Interfaces, IPs, Routing, etc.

# Interfaces (Management already done by Containerlab)
interfaces:
  - if: "Loopback0"
    desc: "Underlay Loopback"
    enabled: true
    ipv4: "10.0.0.22/32"
    ipv6: "2001:db8:c2::1/128"
  - if: "Loopback1"
    desc: "VTEP Loopback"
    enabled: true
    ipv4: "10.0.1.22/32"
  - if: "Ethernet1"
    desc: "ceos-leaf1:Ethernet1 --> ceos-spine1:Ethernet2"
    enabled: true
    routed: true
    v6: true
  - if: "Ethernet2"
    desc: "ceos-leaf1:Ethernet2 --> ceos-spine2:Ethernet2"
    enabled: true
    routed: true
    v6: true

# Routing
router_id: 10.0.0.22
bgp:
  type: "leaf"
  local_as: 65102
  remote_as: 65000
  underlay_pg_id: "PG_UNDERLAY"
  overlay_pg_id: "PG_OVERLAY"
  neighbors:
    underlay:
      - if: "Et1"
      - if: "Et2"
    overlay:
      - ip: "10.0.0.11"
      - ip: "10.0.0.12"
        
# VXLAN

vxlan:
  mac_address: "001c.7301.1eaf"
  vr: True
  range_start: 129
  range_end: 256
  common:
    lacp_id: 5
    host_if: "Ethernet5"
    desc: "ceos-leaf2:eth5 --> ceos-host1:eth2"
    evpn_id: "0050:0900:1eaf:1200:0000"
    evpn_rt: "50:09:00:1e:af:12"
  tenants:
    - id: "TENANT-A"
      host_if: "Ethernet5"
      l2_vlans: [101, 102]
      l3_vlan:
        id: 100
        loop_ip: "172.16.100.12"
        gw_ip: "192.168.100.1/24"
        vni: 1000
    - id: "TENANT-B"
      host_if: "Ethernet5"
      l2_vlans: [201, 202]
      l3_vlan:
        id: 200
        loop_ip: "172.16.200.12"
        gw_ip: "192.168.200.1/24"
        vni: 2000
