# Interfaces (Management already done by Containerlab)
interfaces:
  - if: "Loopback0"
    desc: "BGP Loopback"
    enabled: true
    ipv4: "10.0.0.3/32"
    ipv6: "2001:db8:b3::1/128"
  - if: "Ethernet1"
    desc: "ceos-peer3:Ethernet1 --> ceos-ixp:Ethernet5"
    enabled: true
    routed: true
    ipv4: "192.168.0.13/24"
    ipv6: "2001:db8:ffff::b3/64"

router_id: 10.0.0.3
bgp:
  type: "IXP"
  local_as: 203
  remote_as: 100
  neighbors_v4:
    - ip: "192.168.0.251"
    - ip: "192.168.0.252"
  neighbors_v6:
    - ip: "2001:db8:ffff::1"
    - ip: "2001:db8:ffff::2"
  prefixes_v4_out:
    - prefix: "10.3.0.0/24"
    - prefix: "10.3.1.0/24"
    - prefix: "10.3.2.0/24"
  prefixes_v6_out:
    - prefix: "2001:db8:b31::/48"
    - prefix: "2001:db8:b32::/48"
    - prefix: "2001:db8:b33::/48"