# Interfaces (Management already done by Containerlab)
interfaces:
  - if: "Loopback0"
    desc: "BGP Loopback"
    ipv4: "10.255.1.1/32"
    ipv6: "2001:db8:f11::1/128"
  - if: "Ethernet1"
    desc: "ceos-isp1:Ethernet1 --> ceos-peer1:Ethernet3"
    routed: true
    ipv4: "172.16.0.3/31"
    ipv6: "2001:2:fff1::2/64"
  - if: "Ethernet2"
    desc: "ceos-isp1:Ethernet2 --> ceos-peer2:Ethernet2"
    routed: true
    ipv4: "172.16.0.5/31"
    ipv6: "2001:2:fff2::2/64"