# Separate base VXLAN config from tenants
---
- name: VXLAN
  include_tasks: vxlan.yml
  tags: [ routers, vxlan, base ]

- name: Tenants
  include_tasks: tenants.yml
  loop: 
   - "{{vxlan.tenants}}"
  loop_control:
    loop_var: outer_item
  when:
   - vxlan.tenants is defined
  tags: [ routers, vxlan, tenants ]
