# Separate base VXLAN config from tenants
---
- name: VXLAN
  include_tasks: vxlan.yml
  tags: [ routers, vxlan, base ]

- name: Tenants
  include_tasks: tenants.yml
  tags: [ routers, vxlan, tenants ]
